version: '3'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: onlineAds
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mabaya_online_sponsored_ads:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/onlineAds
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: pass123

volumes:
  postgres_data:
